# Conteúdo Extra
# Python para Análise de Dados - Numpy   

<p> Trabalhando com numpy


In [1]:
# Importando a biblioteca numpy
import numpy as np

In [2]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [3]:
type(one_dim)

numpy.ndarray

In [4]:
# Imprimindo um array.
one_dim.ndim

1

In [5]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
# Imprimindo o array
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.77458927, 0.14800605],
       [0.96946633, 0.41844553],
       [0.0264268 , 0.06748873],
       [0.11839301, 0.43949842],
       [0.60786571, 0.83966313]])

In [8]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso iterar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [11]:
# Criando uma lista em Python.
lista = [1,2,3]

In [12]:
lista

[1, 2, 3]

In [13]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [14]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [15]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [16]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [17]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [18]:
# Faz o calculo usando as listas
pesos/altura**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [20]:
# Imprime o calculo de cada valor
pesos / altura**2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [21]:
# Arrays Numpy armazena elementos como strings quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [22]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')

In [23]:
a*2 

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

# Métodos e Atributos Úteis

In [24]:
# Métodos disponíveis (digite o . pressione tab).
two_dim.

SyntaxError: invalid syntax (<ipython-input-24-538b6f2a23d9>, line 2)

In [25]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [27]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [28]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [29]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [30]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [31]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [32]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
two_dim.dtype

dtype('int32')

In [34]:
two_dim.size

6

In [35]:
# mostra a quantidade
two_dim.itemsize

4

In [36]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [37]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [41]:
tree = np.random.random((5,3))

In [42]:
tree.shape

(5, 3)

In [43]:
tree

array([[0.72968794, 0.75497797, 0.79235148],
       [0.97137436, 0.51622887, 0.7844031 ],
       [0.8281129 , 0.95454643, 0.77690948],
       [0.12363725, 0.0491011 , 0.08697961],
       [0.01742717, 0.51475151, 0.76847145]])

In [44]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.72968794, 0.75497797, 0.79235148, 0.97137436, 0.51622887],
       [0.7844031 , 0.8281129 , 0.95454643, 0.77690948, 0.12363725],
       [0.0491011 , 0.08697961, 0.01742717, 0.51475151, 0.76847145]])

In [45]:
tree.reshape(-1)

array([0.72968794, 0.75497797, 0.79235148, 0.97137436, 0.51622887,
       0.7844031 , 0.8281129 , 0.95454643, 0.77690948, 0.12363725,
       0.0491011 , 0.08697961, 0.01742717, 0.51475151, 0.76847145])

In [46]:
t=tree.reshape(1,15)
t

array([[0.72968794, 0.75497797, 0.79235148, 0.97137436, 0.51622887,
        0.7844031 , 0.8281129 , 0.95454643, 0.77690948, 0.12363725,
        0.0491011 , 0.08697961, 0.01742717, 0.51475151, 0.76847145]])

In [47]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [49]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [50]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [51]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [52]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=dc86eaab-15eb-4e94-8c1d-f6eaae4148b3' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>